# Codecov configuration file
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 40%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "**/R.java"
  - "**/R.kt"
  - "**/R$*.java"
  - "**/R$*.kt"
  - "**/BuildConfig.*"
  - "**/Manifest*.*"
  - "**/*Test*.*"
  - "android/**/*.*"
  - "**/*$WhenMappings.*"
  - "**/*$*$*.*"
  - "**/*Module.*"
  - "**/*_HiltModules*.*"
  - "**/*_Factory*.*"
  - "**/*_MembersInjector*.*"
  - "**/Hilt_*.*"
  - "**/*Component*.*"
  - "**/*_Impl*.*"
  - "**/*Application*.*"
  - "**/di/**/*.*"
